### ISSUE TITLE
Mangler mange fartsgrenser

### ISSUE THREAD

**Issue by NKAmapper** [gomyhr/elveg2osm#12]
Kan det være en feil vedr. fartsgrenser?

Mange veier har ikke fartsgrense i filene som har blitt generert. F.eks. har 1001 Kristiansand bare fartsgrenser for de store hovedveiene. Alle disse veiene har fartsgrense i NVDB. De kan sees ved å gå inn på https://www.vegvesen.no/vegkart/ og så velge "Fartsgrense" + Kategorisering.

Filen Fart.txt som lastes ned fra Elveg for Kristiansand har over 7.000 veisegmenter med fartsgrense 30, men den siste OSM-filen som er generert har bare to veisegmenter med 30.

**Comment by NKAmapper** [comment]
Kan problemet ligge i linje 955?

Der testes det mot "road", men nå brukes i tillegg "unclassified", "residential" og "service".

(Nå manglet riktignok de fleste fartsgrenser også tidligere da mindre veier ble tagget med "road", så kanskje det også er et problem et annet sted i koden).

**Comment by gomyhr** [comment]
Ja, det ser rimelig ut. "road" ble endret til "unclassified", "residential"
og "service", ganske nylig (commit-wise, ikke time-wise ;-), og da ble ikke
denne delen oppdatert. Får du til å teste om det virker som forventet hvis
du legger til "unclassified", "residential" og "service" i lista i linje
955?

Eventuelt kan jeg teste selv når jeg har litt tid ved siden av den PCen som
har Elveg-data og nødvendig oppsett (kan ta noen dager).

(Så kan jeg grave videre når lista over gyldige veier er oppdatert)

**Comment by NKAmapper** [comment]
Det kreves en ganske stor "investering" å sette seg inn i hvordan programmet virker (og særlig fartsgrenser, ser det ut til), så fint om du vil teste først.

Jeg tipper at det også kan være problemer andre steder, siden fartsgrensene også manglet den gang programmet brukte "road".

**Comment by gomyhr** [comment]
Med commit e38814718e15b3eba95bbf39e72516aabfa51d3e, gikk antall veier med fartsgrense 30 i 1001 Kristiansand fra 2 til 1875. Det er totalt 8362 veier der, og 3159 har fartsgrense, og det tror jeg er litt i underkant. Så må vel grave litt mer før jeg setter i gang en ny konvertering.

**Comment by NKAmapper** [comment]
Om det kan være til hjelp, her er fartsgrensene som jeg får direkte ut av NVDB ved hjelp av [nvdb2osm](https://github.com/NKAmapper/nvdb2osm) for vegobjekt 105 (fartsgrense): [filebin](https://filebin.net/qecens2xvsok46jn).

Jeg ser der at en god del stikkveier (private veier og skogsbilveier) har fått fartsgrense 50, som ikke virker riktig. Stikkprøver mot Streetview bekrefter at de ikke stemmer. Noen få av dem er riktignok skiltet med private sorte skilt med fartsgrense, men det kan være helt andre fartsgrenser enn 50. Jeg ville derfor tro at standard fartsgrense 50 for alle service ikke bør tas med. De andre fartsgrensene for service ser ut til å stemme. Og 50 for unclassified or residential ser rimelig ut.

Det er en del trunk og secondary som kommer med fartsgrense 50 fra NVDB. Noen av disse veiene er ikke skiltet med fartsgrense i følge Streetview, men det virker rimelig at de skal ha standard fartsgrense 50 ut i fra bebyggelsen rundt dem og veimerkingen for senterlinje.

(Ellers bør det nevnes at filen fra nvdb2osm bare gir en forenklet geometri - kun senterlinje. Der fartsgrensen er forskjellig forover og bakover vil filen ha to overlappende ways med hver sin fartsgrense. Dette er laget bare for å kunne se på dataene i NVDB. Parameteren -vn vil gi den fullstendige geometrien inkl kjørebaner og turn:lanes).

**Comment by gomyhr** [comment]
Jeg kikket litt mer på dataene i går kveld, og det ser ut som om hoveddelen av de veiene som mangler fartsgrense er veier som har fartsgrense 50 i NVDB. Disse sletter jeg eksplisitt i linje 952, nettopp fordi det står i dokumentasjonen at fartsgrense er satt til 50 for alle veier der det ikke er rapportert inn fartsgrenser. Dermed er det mange av veiene med fartsgrense 50 som slett ikke har det, og det er bedre å bruke andre kilder.

Jeg har satt på generering av nye filer fra det siste datasettet jeg la ut. Så får vi se om noen finner flere mangler når jeg får lastet dem opp.

**Comment by NKAmapper** [comment]
Ok, fint å få flere til å se på dette, og flott at du fikk testet så raskt.

Jeg har hentet ut alle fartsgrense-skiltene i Kristiansand fra NVDB og lagt her: [filebin](url
https://filebin.net/qecens2xvsok46jn). Basert på dette ser jeg at fartsgrense 50 er korrekt for trunk og secondary.

Ellers ser det som sagt ut til at fartsgrense 50 er korrekt for residential, men ikke for service (og unclassified brukes ikke lenger i programmet). Det er disse veitypene som har et høyt antall fartsgrense 50 i NVDB, ikke trunk og secondary (i Kristiansand).

**Comment by gomyhr** [comment]
Nå har jeg oppdatert filene fra juni 2018 på https://drive.google.com/drive/folders/0BwxPkSBawddGN0hUeUZtLUctUW8.

**Comment by NKAmapper** [comment]
Flott. Jeg har tatt en titt på noen av filene. Nå er det aller mest bra, men et par observasjoner:

1) I Kristiansand mangler mange residential-veier maxspeed, blant annet i områdene rundt Gimlekollen og Hånes. Disse veiene er registrert med fartsgrense i NVDB og kan sees på vegkart.no. Flere av fartsgrensene er 30 og 40, dvs ikke bare 50. Har ikke klart å finne ut hvorfor dette skjer.

2) "Residential" mangler i linje 951, eller riktigere: Linje 950-952 bør utgå. Etter vegtrafikkloven er fartsgrensen 50 i tettbygde strøk når det ikke er skiltet, så det er ikke noen grunn til å ikke ta med 50. Siden veiene er kommunale er det en del trafikk på dem og det er ville være nyttig for routerne å vite fartsgrensen. Men interessant å høre hva andre mener siden disse veiene ikke er eksplisitt skiltet med fartsgrense.

3) Som diskutert tidligere i tråden synes jeg fartsgrense ikke bør tas med for service. Godt over 90% av disse veiene er ikke skiltet, de har bare "arvet" fartsgrensen fra naboveien. De fleste er små stikkveier der det ikke så meningsfylt å ha med fartsgrense. En god del lange skogsbilveier som er stengt med bom og som ikke er skiltet har fartsgrense 80 i filene.

**Comment by gomyhr** [comment]
Har sett på punkt 1, og finner ikke noen åpenbare feil, men fint om du peker på dem. Jeg ser at det ikke settes fartsgrense på Astrids vei øst for Tretjønnveien. Fra Google-bilder ser jeg at dette er 30-sone, men veien står med 50 km/t på vegkart.no ([her](https://www.vegvesen.no/nvdb/vegkart/v2/#kartlag:geodata/hva:(~(farge:'0_0,id:105))/@90862,6469258,15/vegobjekt:151797881:40a744:105)). Altså er dette et eksempel på at fartsgrenser 50 km/t fra NVDB/Elveg ikke er til å stole på.
