### ISSUE TITLE
Mulig bug: lanes=* skal inkludere lanes:psv=*

### ISSUE THREAD

**Issue by cmeeren** [gomyhr/elveg2osm#4]
Hvis en vei har tre felt hvorav ett er kollektivfelt, skal den slik jeg forstår [wikien](https://wiki.openstreetmap.org/wiki/Key:lanes:psv) tagges med lanes=3 og lanes:psv=1. Jeg kom over en slik vei som var tagget med lanes=2 i stedet for lanes=3. Kan du sjekke dette?

**Comment by gomyhr** [comment]
De eneste feltkodene som oversettes til lanes=2 og lanes:psv=1 er 1#3K og 2#4K. Disse betyr to felt i samme kjøreretning, hvorav det ene (ytterste) er kollektivfelt. Sistnevnte blir først tagget med oneway=-1, men denne blir nå snudd og den får også oneway=yes. Veien du beskriver høres ut som en 1#3#5K (alle felt samme retning) eller 1#2#3K (ikke-kollektivfelt i forskjellige retninger).

Generelt, hvis du ser noe tagging du stusser på, så sjekk hva Elveg-tagginga er i Elveg_default.osm. Det hender at disse ikke stemmer med virkeligheten.

Jeg har bare oversatt lane-tagger som har over 100 forekomster totalt sett. Av disse er alle veier med kollektivfelt enveiskjørt. Fire felt hvorav de to ytterste kollektivfelt (1#2#3K#4K) skulle man tro var vanlig, men kommer lenger ned på lista (52 forekomster).

**Comment by cmeeren** [comment]
Jeg hadde sett feil. Sjekket data igjen nå og veien var 1#3, da uten kollektivfeltet som har kommet der (Elveg var ikke oppdatert). Det var ingen lanes:psv i Elveg, dette var på eksisterende veg og jeg bare blingset litt.
