### ISSUE TITLE
Behold nvdb:date hvis den er lik på sammenslåtte veistykker

### ISSUE THREAD

**Issue by ghost** [gomyhr/elveg2osm#6]
Antakeligvis er så datoen på en del av veiene lik. Det  hadde vært interessant å tatt vare på den.

Jeg tenkte jeg skulle visualisere veiene som sprer seg utover i kommunen med den.
Vet ikke om det er interessant for andre eller om det er trøblete å implementere.

**Comment by gomyhr** [comment]
Jeg synes det blir inkonsistent å holde på (og importere i OSM) nvdb:date når vi tar bort nvdb:id. Men for visualisering er det enkelt å kommentere ut linja:
way.tags.pop('nvdb:date')
(p.t. linje 517 - i starten av merge_equal)
Den vil da la være å slå sammen vegstykker der nvdb:date er forskjellig. Alternativt kan du sjekke ut en versjon som ikke slår sammen veier, f.eks. commit f7786dd1e87214b93f948370003bb8f84b18cf31 (fra 23. august).

Hvis du ikke får infrastrukturen på plass (du trenger ikke sosi2osm hvis du bruker XXXXElveg_default.osm og tekstfiler lastet ned fra kartverket som input), kan jeg lage filer for et par kommuner til deg.

**Comment by ghost** [comment]
Jeg har importert en kommune med date: og :id på alt. Tenkte jeg skulle lage den overnevnte "tidsmaskinen". Og jeg har forsåvidt kommunefiler med og uten :date og :id, men greit.
Det var dramatisk mye kjappere å importere med longways og droppe date: og :id, så jeg tviler det er verdt det.
