### ISSUE TITLE
Fartsgrense spesifikk for felt

### ISSUE THREAD

**Issue by cmeeren** [gomyhr/elveg2osm#7]
elveg2osm tagger nå fartsgrense globalt for vegen, selv om XXXXFart.txt iblant inneholder informasjon som gir ulike felt (kjøreretninger) egen fartsgrense. Dette bør plukkes opp, slik at maxspeed:forward og :backward brukes, evt. maxspeed:lanes:forward ved mer kompliserte tilfeller.

Slik jeg ser det trengs følgende endringer:
- [Her](https://github.com/gomyhr/elveg2osm/blob/db028770e4ab0699bab9a315a70ec9bdd4d2d08e/elveg2osm.py#L622-L624) må feltkoden legges inn i dictionary sammen med maxspeed, start og stopp.
- [Her](https://github.com/gomyhr/elveg2osm/blob/db028770e4ab0699bab9a315a70ec9bdd4d2d08e/elveg2osm.py#L724) må feltlogikken skrives. Foreslår følgende enkle logikk i denne omgang: Hvis feltkoden for restriksjonen matcher VKJORFLT, bruk maxspeed. Ellers hvis feltkoden kun inneholder oddetall, bruk maxspeed:forward. Tilsvarende med partall og maxspeed:backward. Jeg er imidlertid usikker på hvordan man finner veiens VKJORFLT på dette stedet i koden (hvis den er utilgjengelig kan det være en workaround å sende feltkoden in i `parse_lanes` og sammenligne med OSM tags på veien, men kjenner ikke koden godt nok til å være trygg på at dette er robust).

**Comment by gomyhr** [comment]
Da har jeg fått til en slags implementasjon av dette i commit 30c54f1501a4faca. Når man begynner å se på hvor felt-kolonna i XXXXFart.txt ikke stemmer med det som står i SOSI-fila, er det oftere feil enn at det er forskjellige fartsgrenser i forskjellige felt. Til slutt endte jeg med å kun tagge maxspeed:forward og maxspeed:backward selv om det ofte ser ut som om bare ett av feltene på to- og tre-felts enveiskjørte veier har fartsgrense. Det skrives til loggen hver gang forskjeller detekteres som ikke tas hensyn til.

**Comment by cmeeren** [comment]
Ypperlig. Noe mer omfattende enn jeg trodde pga. cleanup som var nødvendig. Takk! :+1:
