### ISSUE TITLE
error ved extracting

### ISSUE THREAD

**Issue by ablohme86** [gomyhr/elveg2osm#8]
elveg2osm.py 0101Elveg.SOS
Traceback (most recent call last):
  File "/usr/local/bin/elveg2osm.py", line 587, in <module>
    kummune_int = int(kommune_number)
ValueError: invalid literal for int() with base 10: '.SOS'

**Comment by gomyhr** [comment]
elveg2osm does not take the SOSI files from Elveg as input. Rather, use sosi2osm for converting from SOSI format to OSM format. Elveg2osm then takes this output together with the *.txt files from Elveg and coverts to an OSM file with meaningful tagging. See the Usage section in README.md for details.

Sent from my phone
