### ISSUE TITLE
Feil tag på ferry_terminal

### ISSUE THREAD

**Issue by Reitstoen** [gomyhr/elveg2osm#9]
Det er skrevet med mellomrom. Skal være underscore.
linje 826: noway_node.tags['amenity'] = 'ferry terminal'

**Comment by gomyhr** [comment]
Merget FredrikLinseth sin pull request, som fikser dette.

**Comment by gomyhr** [comment]
Dette skal forresten være tatt med i siste elveg2osm output som jeg har lagt ut på https://drive.google.com/folderview?id=0BwxPkSBawddGN0hUeUZtLUctUW8&usp=sharing. Folder Elveg_2016-05-21.
